# Generated by Django 4.1.2 on 2022-11-20 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('primary', models.CharField(max_length=100)),
                ('secondary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('benchmng', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('status', models.CharField(default='NA', max_length=100)),
                ('panel', models.CharField(default='NA', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
