# Generated by Django 4.1.2 on 2022-11-29 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('interviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('count', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=100)),
                ('reqPrimary', models.CharField(max_length=100)),
                ('reqSecondary', models.CharField(max_length=100)),
                ('reqEmail', models.CharField(max_length=100)),
                ('reqLocation', models.CharField(max_length=100)),
                ('reqGrade', models.CharField(max_length=10)),
                ('reqCount', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=100)),
                ('empFullname', models.CharField(max_length=100)),
                ('empEmail', models.CharField(max_length=100)),
                ('empPrimary', models.CharField(max_length=100)),
                ('empSecondary', models.CharField(max_length=100)),
                ('empLocation', models.CharField(max_length=100)),
                ('empDesignation', models.CharField(max_length=100)),
                ('empBenchmng', models.CharField(max_length=100)),
                ('empRemarks', models.CharField(max_length=200)),
                ('empStatus', models.CharField(default='NA', max_length=100)),
                ('empPanel', models.CharField(default='NA', max_length=100)),
                ('empDate', models.DateField(default=datetime.date.today)),
                ('interviewer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employee_register.interviewer')),
            ],
        ),
    ]
