# Generated by Django 4.1.2 on 2022-10-31 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='seondary',
            new_name='secondary',
        ),
    ]
