# Generated by Django 4.1.2 on 2022-11-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
    ]
