# Generated by Django 4.1.2 on 2023-01-17 07:31

from django.db import migrations, models
import django.db.models.deletion
import employee_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='CVPath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='interviewer',
            field=models.ForeignKey(default=employee_register.models.Interviewer.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee_register.interviewer'),
        ),
    ]
