# Generated by Django 4.1.2 on 2022-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_rename_seondary_employee_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
