# Generated by Django 4.1.2 on 2022-11-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='benchmng',
            new_name='empBenchmng',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date',
            new_name='empDate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='empDesignation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='empEmail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='empFullname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='location',
            new_name='empLocation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='panel',
            new_name='empPanel',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='primary',
            new_name='empPrimary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='remarks',
            new_name='empRemarks',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='secondary',
            new_name='empSecondary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='empStatus',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='grade',
            new_name='reqGrade',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='location',
            new_name='reqLocation',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='primary',
            new_name='reqPrimary',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='secondary',
            new_name='reqSecondary',
        ),
    ]
