# Generated by Django 4.1.2 on 2022-11-19 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_remove_employee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
