# Generated by Django 4.1.2 on 2022-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_employee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='EmpStatus',
        ),
    ]
