# Generated by Django 4.1.2 on 2022-12-19 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_alter_employee_emptimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 13, 0, 35, 956703)),
        ),
    ]
