# Generated by Django 4.1.2 on 2022-12-19 07:35

import builtins
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_register', '0005_alter_employee_emptimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 13, 5, 0, 423017)),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='user_id',
            field=models.ForeignKey(default=builtins.input, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
