# Generated by Django 4.1.2 on 2022-12-19 07:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_register', '0008_remove_interviewer_user_id_interviewer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 13, 18, 53, 845715)),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
