# Generated by Django 4.1.2 on 2022-12-19 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_alter_employee_emptimestamp_alter_interviewer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 21, 18, 19, 985856)),
        ),
    ]
